### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by tvercaut** [openreview/openreview-scripts#1095]
Looking at files such as [get-reviewers.py](https://github.com/iesl/openreview-scripts/blob/master/samples/python/get-reviewers.py), it is apparent that the code relies on python2 (e.g. `print` statements). 

Given that "Python 2.x will reach the end of its life on January 1st, 2020", it would be fantastic to make sure the code is compatible with python3.

**Comment by melisabok** [comment]
We are supporting python 2 and 3. There are some scripts in this repo that are old and we haven't updated them to python 3.
